### PR TITLE
Fix add player

### LINKED ISSUE #826: JS crashes when adding a new player to an ongoing tournament

### PR DESCRIPTION
**Pull request by domino14**
fix #826

### CODE REVIEW

File: pkg/tournament/classic_division.go [hunk 1]
```diff
@@ -952,6 +955,7 @@ func (t *ClassicDivision) RemovePlayers(persons *realtime.TournamentPersons) (*r
 				return nil, err
 			}
 			pairingsMessage.DivisionStandings = combineStandingsResponses(pairingsMessage.DivisionStandings, map[int32]*realtime.RoundStandings{int32(i): roundStandings})
+			t.Standings[int32(i)] = roundStandings
```
Comment (jvc56) [inline pkg/tournament/classic_division.go:958]: Oops. This suggestion that was mine doesn't actually fix anything. I've messaged you with the REAL answer.

**Review by jvc56 — APPROVED** [review]
